globals:
  framerate: 24
  width: 1920
  height: 1080
  output_codec: prores
  font_size: 30
  ffmpeg_bin: /Users/sam/roots/ffmpeg-ocio-8.1/bin/ffmpeg
  font:
    darwin: /System/Library/Fonts/Helvetica.ttc
    linux: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
    win32: C:/Windows/Fonts/arial.ttf
output_codecs:
  h264_hq:
    codec: libx264
    crf: 18
    preset: slow
    pix_fmt: yuv420p10le
  png_lossless:
    codec: png
    pix_fmt: rgba
  prores:
    codec: prores_ks
    pix_fmt: yuv444p10le
    profile: 4444
metadata:
  Notes: "Sample Note:\n * did this\n * Did something else.\n"
  Vendor Name: Test Vendor
  Show Title: Sample Show
  Version: v74
  Shot: 'RAP_090'
  Date Delivered: 2026-02-27 14:05
slate:
  template_image: base_slate.exr
  thumbnail_enabled: true
  fields:
    Show:
      text: '{Show Title}'
      x: 140
      y: 139
      font_size: 90
    Vendor:
      text: 'Vendor:  {Vendor Name}'
      x: 140
      y: 560
      font_size: 30
    Date:
      text: '{Date Delivered}'
      x: 140
      y: 245
      font_size: 33
    Notes:
      text: '{Notes}'
      x: 140
      y: 640
      font_size: 30
    File Name:
      text: 'File: {File Name}'
      x: 140
      y: 516
      font_size: 30
    Version:
      text: '{Version}'
      x: 1766
      y: 534
      font_size: 44
    Frame Range:
      text: 'Frames: {Frame Range}'
      x: 140
      y: 827
      font_size: 30
    Shot:
      text: '{Shot}'
      x: 140
      y: 332
      font_size: 57
  thumbnail_x: 1028
  thumbnail_y: 83
  thumbnail_width: 826
burnins:
  layout:
    lower_left: '{Notes}'
    lower_center: '{Vendor Name}'
    lower_right: '{frame}'
    top_left: '{File Name}'
    top_center: '{Show Title}'
    top_right: '{Date Delivered}'
  fonts:
    lower_left: /System/Library/Fonts/Helvetica.ttc
    lower_center: /System/Library/Fonts/Helvetica.ttc
ocio:
  enabled: true
  config_path: /Users/sam/git/ffmpeg-ocio-test/sourcemedia/studio-config-v1.0.0_aces-v1.3_ocio-v2.1_ns.ocio
  input_space: ACEScg
  output_space: sRGB - Display
  view: ACES 1.0 - SDR Video
