globals:
  framerate: 24
  width: 1920
  height: 1080
  output_codec: prores
  font_size: 30
  font:
    darwin: /System/Library/Fonts/Helvetica.ttc
    linux: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
    win32: C:/Windows/Fonts/arial.ttf
  metadata_mapping:
    Shot: shot
    Version: version
    Frame Range: frame_range
    first_frame: first_frame
    last_frame: last_frame
    source_frame_rate: source_frame_rate
    slate_length: slate_length
    display_type: display_type
    watermarking: watermarking
    source_filename: source_filename
  vf: "scale=in_color_matrix=bt709:out_color_matrix=bt709"
  args: ["-color_primaries", "bt709", "-color_trc", "iec61966-2-1", "-colorspace", "bt709"]
output_codecs:
  h264_hq:
    codec: libx264
    crf: 18
    preset: slow
    pix_fmt: yuv420p10le
  png_lossless:
    codec: png
    pix_fmt: rgba
  prores:
    codec: prores_ks
    pix_fmt: yuv444p10le
    profile: 4444
metadata:
  Notes: "Sample Note:\n * did this\n * Did something else.\n"
  Vendor Name: Test Vendor
  Show Title: Sample Show
  Date Delivered: 2026-02-27 14:05
dynamic_metadata:
  enabled: true
  rules:
  - target: Shot
    source: File Name
    regex: ^([A-Z0-9]+)
  - target: Version
    source: File Name
    regex: (v\d+)
slate:
  enabled: true
  template_image: base_slate.exr
  thumbnail_enabled: true
  fields:
    Show:
      text: '{Show Title}'
      x: 140
      y: 139
      font_size: 90
      align: left
      max_width: 0
      max_height: 0
    Vendor:
      text: 'Vendor:  {Vendor Name}'
      x: 901
      y: 675
      font_size: 30
      align: left
      max_width: 612
      max_height: 46
    Date:
      text: '{Date Delivered}'
      x: 140
      y: 245
      font_size: 33
      align: left
      max_width: 0
      max_height: 0
    Notes:
      text: '{Notes}'
      x: 140
      y: 640
      font_size: 30
      align: left
      max_width: 561
      max_height: 141
    File Name:
      text: 'File: {File Name}'
      x: 140
      y: 517
      font_size: 30
      align: left
      max_width: 539
      max_height: 47
    Version:
      text: '{Version}'
      x: 1616
      y: 563
      font_size: 44
      align: right
      max_width: 231
      max_height: 0
    Frame Range:
      text: 'Frames: {Frame Range}'
      x: 140
      y: 827
      font_size: 30
      align: left
      max_width: 0
      max_height: 0
    Shot:
      text: '{Shot}'
      x: 140
      y: 332
      font_size: 57
      align: left
      max_width: 0
      max_height: 0
    Timecode:
      text: 'TC: {timecode}'
      x: 140
      y: 400
      font_size: 40
      align: left
      max_width: 0
      max_height: 0
    Reel:
      text: 'Reel: {reel}'
      x: 140
      y: 450
      font_size: 30
      align: left
      max_width: 0
      max_height: 0
  thumbnail_x: 1028
  thumbnail_y: 83
  thumbnail_width: 828
burnins:
  font_size: 40
  font_color: white
  background_color: black@0.5
  layout:
    lower_left: '{Notes}'
    lower_center: '{Vendor Name}'
    lower_right: '{timecode} {frame}'
    top_left: '{File Name}'
    top_center: '{Show Title}'
    top_right: '{Date Delivered}'
ocio:
  enabled: true
  config_path: ../ffmpeg-ocio-test/sourcemedia/studio-config-v1.0.0_aces-v1.3_ocio-v2.1_ns.ocio
  input_space: ACEScg
  output_space: sRGB - Display
  view: ACES 1.0 - SDR Video
